# Generated by Django 4.0.4 on 2022-04-30 17:36

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('last_name', models.CharField(max_length=255, verbose_name='Ազգանուն')),
                ('email', models.CharField(max_length=255, verbose_name='Էլ. հասցե')),
                ('message', models.TextField(verbose_name='Նամակ')),
            ],
            options={
                'verbose_name': 'Հարցում',
                'verbose_name_plural': 'Հարցումներ',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])], verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Նկար',
                'verbose_name_plural': 'Նկարներ',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Դասավերնագիր')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ամբողջական տեքստ')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Հակիրճ տեքստ')),
                ('image', models.FileField(upload_to='', verbose_name='Նկար')),
            ],
            options={
                'verbose_name': 'Դասընթաց',
                'verbose_name_plural': 'Դասընթացներ',
            },
        ),
    ]
