# Generated by Django 4.0.4 on 2022-04-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Հետադարձ կապի պատվեր', 'verbose_name_plural': 'Հետադարձ կապի պատվերներ'},
        ),
    ]
