# Generated by Django 4.0.4 on 2022-05-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='short_text',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.FileField(default=1, upload_to='', verbose_name='Նկար'),
            preserve_default=False,
        ),
    ]
