# Generated by Django 4.0.4 on 2022-05-01 20:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_aboutus_short_text_aboutus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='large_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Տեքստ'),
        ),
    ]
