# Generated by Django 4.0.4 on 2022-05-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_aboutus_large_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='show_in_about_us',
            field=models.BooleanField(default=False, verbose_name='Ցուցադրել «Մեր մասին» էջում'),
        ),
    ]
