# Generated by Django 4.0.4 on 2022-05-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lessons_show_in_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Անուն')),
            ],
        ),
        migrations.CreateModel(
            name='LessonImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Նկար')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='show_in_about_us',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default=111, max_length=255, verbose_name='Հեռ.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonimages',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lessons'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='cls',
            field=models.ForeignKey(default=2111, on_delete=django.db.models.deletion.CASCADE, to='app.classes', verbose_name='Դասարանը'),
            preserve_default=False,
        ),
    ]
