# Generated by Django 4.0.4 on 2022-05-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_classes_lessonimages_delete_aboutus_delete_gallery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Դասարան', 'verbose_name_plural': 'Դասարաններ'},
        ),
    ]
